[context.branch-deploy.environment]
    NODE_VERSION = "18.18.0"
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID = "pwqmodw2ib46"
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = "mHhLK3ekYEg7EHUS0ES5WembjqYWOuzovXjIq6b9rXs"
    NEXT_PUBLIC_CONTENTFUL_MANAGEMENT_TOKEN = "CFPAT-Wlg20sQG3jzIQPFaIWCGrU9OxwAd2lm6VpSF8bcWLQI"
    NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT = "dev"
    NEXT_PUBLIC_GOOGLE_API_KEY = "AIzaSyDpuVxa-qgT5o1_I3qmoEYnOGkoJIJcMBk"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = "567840947369-45nrrb14lepnnabbt6af75odm1v3bo73.apps.googleusercontent.com"
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET = "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"
    NEXT_PUBLIC_GOOGLE_EMAIL = "flashback.rocks.rh@gmail.com"
    GOOGLE_PASSWORD = "xljz ltgz xgmv luiv"

[context.dev.environment]
    NODE_VERSION = "18.18.0"
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID = "pwqmodw2ib46"
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = "mHhLK3ekYEg7EHUS0ES5WembjqYWOuzovXjIq6b9rXs"
    NEXT_PUBLIC_CONTENTFUL_MANAGEMENT_TOKEN = "CFPAT-Wlg20sQG3jzIQPFaIWCGrU9OxwAd2lm6VpSF8bcWLQI"
    NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT = "dev"
    NEXT_PUBLIC_GOOGLE_API_KEY = "AIzaSyDpuVxa-qgT5o1_I3qmoEYnOGkoJIJcMBk"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = "567840947369-45nrrb14lepnnabbt6af75odm1v3bo73.apps.googleusercontent.com"
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET = "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"
    NEXT_PUBLIC_GOOGLE_EMAIL = "flashback.rocks.rh@gmail.com"
    GOOGLE_PASSWORD = "xljz ltgz xgmv luiv"


[context.deploy-preview.environment]
    NODE_VERSION = "18.18.0"
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID = "pwqmodw2ib46"
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = "mHhLK3ekYEg7EHUS0ES5WembjqYWOuzovXjIq6b9rXs"
    NEXT_PUBLIC_CONTENTFUL_MANAGEMENT_TOKEN = "CFPAT-Wlg20sQG3jzIQPFaIWCGrU9OxwAd2lm6VpSF8bcWLQI"
    NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT = "dev"
    NEXT_PUBLIC_GOOGLE_API_KEY = "AIzaSyDpuVxa-qgT5o1_I3qmoEYnOGkoJIJcMBk"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = "567840947369-45nrrb14lepnnabbt6af75odm1v3bo73.apps.googleusercontent.com"
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET = "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"
    NEXT_PUBLIC_GOOGLE_EMAIL = "flashback.rocks.rh@gmail.com"
    GOOGLE_PASSWORD = "xljz ltgz xgmv luiv"


[context.production.environment]
    NODE_VERSION = "18.18.0"
    NEXT_PUBLIC_CONTENTFUL_SPACE_ID = "pwqmodw2ib46"
    NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN = "mHhLK3ekYEg7EHUS0ES5WembjqYWOuzovXjIq6b9rXs"
    NEXT_PUBLIC_CONTENTFUL_MANAGEMENT_TOKEN = "CFPAT-Wlg20sQG3jzIQPFaIWCGrU9OxwAd2lm6VpSF8bcWLQI"
    NEXT_PUBLIC_CONTENTFUL_ENVIRONMENT = "master"
    NEXT_PUBLIC_GOOGLE_API_KEY = "AIzaSyDpuVxa-qgT5o1_I3qmoEYnOGkoJIJcMBk"
    NEXT_PUBLIC_GOOGLE_CLIENT_ID = "567840947369-45nrrb14lepnnabbt6af75odm1v3bo73.apps.googleusercontent.com"
    NEXT_PUBLIC_GOOGLE_CLIENT_SECRET = "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"
    NEXT_PUBLIC_GOOGLE_EMAIL = "flashback.rocks.rh@gmail.com"
    GOOGLE_PASSWORD = "xljz ltgz xgmv luiv"
